# Generated by Django 2.0.4 on 2018-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintimeline', '0003_event_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approx_year',
            field=models.NullBooleanField(),
        ),
    ]
