# Generated by Django 2.0.4 on 2018-04-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintimeline', '0004_event_approx_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
